spring:
  application:
    name: remote-hsm-client
server:
  servlet:
    context-path: /rhsm-client
  port: 8080
credential:
  bundles:
    jks:
      wallet-1-gen:
        name: "Wallet 1 - General context"
        store-reference: wallet-gen
        key:
          alias: wallet-gen
          key-password: Test1234
        key-id: wallet-gen-key-1
        metadata:
          jws-algorithm: ES256
          keyuse: sign
      wallet-1-hsm:
        name: "Wallet 1 - HSM context"
        store-reference: wallet-hsm
        key:
          alias: wallet-hsm
          key-password: Test1234
        key-id: wallet-hsm-key-1
        metadata:
          jws-algorithm: ES256
          keyuse: sign
    keystore:
      wallet-gen:
        location: classpath:dev/wallet-gen.p12
        password: Test1234
        type: PKCS12
      wallet-hsm:
        location: classpath:dev/wallet-hsm.p12
        password: Test1234
        type: PKCS12
    monitoring:
      health-endpoint-enabled: false
rps-ops-client:
  client-identity: https://wallets/digg.se/1234567890
  contexts:
    wallet:
      key: wallet-1-gen
      server-certificate-location: classpath:dev/server/bff-gen.crt
      server-identity: https://cloud-wallet.digg.se/bff
    hsm:
      key: wallet-1-hsm
      server-certificate-location: classpath:dev/server/server-key.crt
      server-identity: https://cloud-wallet.digg.se/rhsm
  server-url: http://localhost:8090/rhsm-bff
  service-path: /service
  session-duration: PT15M
logging:
  level:
    se:
      digg:
        wallet: DEBUG

